/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as MovieMovieIdRouteImport } from './routes/movie.$movieId'
import { Route as WatchFilmIdRouteImport } from './routes/watch.$filmId'
import { Route as ApiPublicSubtitlesRouteImport } from './routes/api/public/subtitles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchFilmIdRoute = WatchFilmIdRouteImport.update({
  id: '/watch/$filmId',
  path: '/watch/$filmId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubtitlesRoute = ApiPublicSubtitlesRouteImport.update({
  id: '/api/public/subtitles',
  path: '/api/public/subtitles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/watch/$filmId': typeof WatchFilmIdRoute
  '/api/public/subtitles': typeof ApiPublicSubtitlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/watch/$filmId': typeof WatchFilmIdRoute
  '/api/public/subtitles': typeof ApiPublicSubtitlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/watch/$filmId': typeof WatchFilmIdRoute
  '/api/public/subtitles': typeof ApiPublicSubtitlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/downloads'
    | '/profile'
    | '/search'
    | '/shorts'
    | '/movie/$movieId'
    | '/watch/$filmId'
    | '/api/public/subtitles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/downloads'
    | '/profile'
    | '/search'
    | '/shorts'
    | '/movie/$movieId'
    | '/watch/$filmId'
    | '/api/public/subtitles'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/downloads'
    | '/profile'
    | '/search'
    | '/shorts'
    | '/movie/$movieId'
    | '/watch/$filmId'
    | '/api/public/subtitles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DownloadsRoute: typeof DownloadsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  ShortsRoute: typeof ShortsRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
  WatchFilmIdRoute: typeof WatchFilmIdRoute
  ApiPublicSubtitlesRoute: typeof ApiPublicSubtitlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$filmId': {
      id: '/watch/$filmId'
      path: '/watch/$filmId'
      fullPath: '/watch/$filmId'
      preLoaderRoute: typeof WatchFilmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subtitles': {
      id: '/api/public/subtitles'
      path: '/api/public/subtitles'
      fullPath: '/api/public/subtitles'
      preLoaderRoute: typeof ApiPublicSubtitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DownloadsRoute: DownloadsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  ShortsRoute: ShortsRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
  WatchFilmIdRoute: WatchFilmIdRoute,
  ApiPublicSubtitlesRoute: ApiPublicSubtitlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
